CREATE TABLE [dbo].[Table]
(
	[StaffID] NVARCHAR(MAX) NOT NULL PRIMARY KEY, 
    [FSNameA] NVARCHAR(MAX) NOT NULL, 
    [MSNameA] NVARCHAR(MAX) NOT NULL, 
    [LSNameA] NVARCHAR(MAX) NOT NULL, 
    [NaSID] INT NOT NULL, 
    CONSTRAINT [PK_Table] PRIMARY KEY ([StaffID]), 
    CONSTRAINT [PK_Table] PRIMARY KEY ([StaffID]), 
    CONSTRAINT [PK_Table] PRIMARY KEY ([NaID])
)
